# Generated by Django 6.0.1 on 2026-02-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(
                choices=[
                    ('cash_on_delivery', 'Cash on Delivery'),
                    ('mobile_money', 'Mobile Money'),
                    ('card', 'Card'),
                ],
                default='cash_on_delivery',
                max_length=30,
            ),
        ),
    ]
