# Generated by Django 6.0.1 on 2026-02-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('MTN', 'MTN Mobile Money'), ('AIRTEL', 'Airtel Money'), ('CASH', 'Cash on Delivery')], default='MTN', max_length=20),
        ),
    ]
